name: Release

on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}
    permissions: write-all
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            toolchain: 1.89.0-x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            toolchain: 1.89.0-x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
          - target: x86_64-apple-darwin
            toolchain: 1.89.0-x86_64-apple-darwin
            archive: zip
    steps:
      - uses: actions/checkout@main
      - name: Compile and release
        uses: hardglitch/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          TOOLCHAIN_VERSION: ${{ matrix.toolchain }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          MINIFY: false